# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

upgrade:
  source: cdn
  interval: 168h
  auto: false
  notice: false
blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - template: "root <#ffffff>in</> "
        foreground: "#E06C75"
        type: root
        style: plain
      - template: "{{ .Path }} "
        foreground: "#55B9C4"
        type: path
        style: plain
        properties:
          style: unique
          # mapped_locations:
          #   /Users/umang: 🏠
      - template: "<#ffffff>on</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} "
        foreground: "#C678DD"
        type: git
        style: plain
        properties:
          fetch_status: true
  - type: prompt
    alignment: left
    newline: true
    segments:
      - template: "{{ if eq .Code 0 }}<#63F08C>\u276f{{ else }}<#e91e63>\u2718{{ end }} "
        foreground: "#63F08C"
        type: status
        style: plain
        properties:
          always_enabled: true
version: 3
